#!/bin/sh

if [ "x$MSYSTEM" != "x" ] ; then
  EXEEXT=".exe"
  LIBEXT="dll"
else
  EXEEXT=""
  LIBEXT="so"
fi

echo Creating output directory tree

mkdir -p output29/share/codeblocks_con/plugins
mkdir -p output29/share/codeblocks_con/scripts
mkdir -p devel29/share/codeblocks_con/plugins
mkdir -p devel29/share/codeblocks_con/scripts

ZIPCMD="zip"
RESDIR="devel29/share/codeblocks_con"
echo Compressing core UI resources
echo Compressing plugins UI resources
${ZIPCMD} -jqu9 ${RESDIR}/compiler.zip plugins/compilergcc/resources/manifest.xml > /dev/null

echo Copying files
# Create an exclude pattern file
echo .svn > excludes.txt
echo Makefile >> excludes.txt
echo Makefile.am >> excludes.txt
echo Makefile.in >> excludes.txt
cp -f ${RESDIR}/*.zip output29/share/codeblocks_con > /dev/null
cp -f scripts/*.script ${RESDIR}/scripts > /dev/null
cp -f scripts/*.script output29/share/codeblocks_con/scripts > /dev/null
cp -f devel29/codeblocks_con${EXEEXT} output29 > /dev/null
cp -f devel29/*.${LIBEXT} output29 > /dev/null
cp -f ${RESDIR}/plugins/*.${LIBEXT} output29/share/codeblocks_con/plugins > /dev/null
# Now remove the exclude pattern file
rm excludes.txt

echo Stripping debug info from output tree
strip output29/codeblocks_con${EXEEXT}
strip output29/*.${LIBEXT}
strip output29/share/codeblocks_con/plugins/*.${LIBEXT}

if [ "x$MSYSTEM" = "x" ] ; then
  echo "#!/bin/sh" > output29/run_con.sh
  echo 'APP_DIR=`dirname "$0"`' >> output29/run_con.sh
  echo 'APP_DIR=`( cd "$APP_DIR" && pwd )`' >> output29/run_con.sh
  echo "export LD_LIBRARY_PATH=\$APP_DIR:\$LD_LIBRARY_PATH" >> output29/run_con.sh
  echo "\$APP_DIR/codeblocks_con \$@" >> output29/run_con.sh
  chmod +x output29/run_con.sh
  echo "#!/bin/sh" > devel29/run_con.sh
  echo 'APP_DIR=`dirname "$0"`' >> devel29/run_con.sh
  echo 'APP_DIR=`( cd "$APP_DIR" && pwd )`' >> devel29/run_con.sh
  echo "export LD_LIBRARY_PATH=\$APP_DIR:\$LD_LIBRARY_PATH" >> devel29/run_con.sh
  echo "\$APP_DIR/codeblocks_con \$@" >> devel29/run_con.sh
  chmod +x devel29/run_con.sh
fi

ZIPCMD=
RESDIR=
