#!/bin/sh

if [ "x$MSYSTEM" != "x" ] ; then
  EXEEXT=".exe"
  LIBEXT="dll"
else
  EXEEXT=""
  LIBEXT="so"
fi

echo Creating output directory tree

mkdir -p output/share/codeblocks/plugins
mkdir -p devel/share/codeblocks/plugins

ZIPCMD="zip"
RESDIR="devel/share/codeblocks"
echo Compressing core UI resources
echo Compressing plugins UI resources
${ZIPCMD} -jqu9 ${RESDIR}/con_compiler.zip plugins/compilergcc/resources/manifest.xml > /dev/null

echo Copying files
# Create an exclude pattern file
echo .svn > excludes.txt
echo Makefile >> excludes.txt
echo Makefile.am >> excludes.txt
echo Makefile.in >> excludes.txt
cp -fu ${RESDIR}/*.zip output/share/codeblocks > /dev/null
cp -fu devel/codeblocks_con${EXEEXT} output > /dev/null
cp -fu devel/*.${LIBEXT} output > /dev/null
cp -fu ${RESDIR}/plugins/*.${LIBEXT} output/share/codeblocks/plugins > /dev/null
# Now remove the exclude pattern file
rm excludes.txt

echo Stripping debug info from output tree
strip output/codeblocks_con${EXEEXT}
strip output/*.${LIBEXT}
strip output/share/codeblocks/plugins/*.${LIBEXT}

if [ "x$MSYSTEM" = "x" ] ; then
  echo "#!/bin/sh" > output/run_con.sh
  echo 'APP_DIR=`dirname "$0"`' >> output/run_con.sh
  echo 'APP_DIR=`( cd "$APP_DIR" && pwd )`' >> output/run_con.sh
  echo "export LD_LIBRARY_PATH=\$APP_DIR:\$LD_LIBRARY_PATH" >> output/run_con.sh
  echo "\$APP_DIR/codeblocks_con \$@" >> output/run_con.sh
  chmod +x output/run_con.sh
  echo "#!/bin/sh" > devel/run_con.sh
  echo 'APP_DIR=`dirname "$0"`' >> devel/run_con.sh
  echo 'APP_DIR=`( cd "$APP_DIR" && pwd )`' >> devel/run_con.sh
  echo "export LD_LIBRARY_PATH=\$APP_DIR:\$LD_LIBRARY_PATH" >> devel/run_con.sh
  echo "\$APP_DIR/codeblocks_con \$@" >> devel/run_con.sh
  chmod +x devel/run_con.sh
fi

ZIPCMD=
RESDIR=
